/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author 04590876060
 */
public class TelaVincularDoenca extends javax.swing.JFrame {

    /**
     * Creates new form TelaVincularDoenca
     */
    
    TelaHome th;
    
    public TelaVincularDoenca(TelaHome th) {
        initComponents();
        this.th=th;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDoenca = new javax.swing.ButtonGroup();
        buttonGroupSintoma = new javax.swing.ButtonGroup();
        jpanelTitulo3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpanelInput1 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtDoenca = new javax.swing.JTextField();
        lblTextoDoenca = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        rbtnIdDoenca = new javax.swing.JRadioButton();
        rbtnDoenca = new javax.swing.JRadioButton();
        txtSintoma = new javax.swing.JTextField();
        rbtnSintoma = new javax.swing.JRadioButton();
        rbtnIdSintoma = new javax.swing.JRadioButton();
        lblTextoSintoma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Vincular sintoma a doença");

        jpanelTitulo3.setBackground(new java.awt.Color(51, 51, 255));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DiagWeb");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        javax.swing.GroupLayout jpanelTitulo3Layout = new javax.swing.GroupLayout(jpanelTitulo3);
        jpanelTitulo3.setLayout(jpanelTitulo3Layout);
        jpanelTitulo3Layout.setHorizontalGroup(
            jpanelTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelTitulo3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelTitulo3Layout.setVerticalGroup(
            jpanelTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelTitulo3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        jpanelInput1.setBackground(new java.awt.Color(153, 153, 255));

        btnExcluir.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setFocusPainted(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtDoenca.setSelectedTextColor(new java.awt.Color(204, 255, 255));
        txtDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoencaActionPerformed(evt);
            }
        });

        lblTextoDoenca.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoDoenca.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblTextoDoenca.setText("Digite o nome da doença:");

        btnAlterar.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.setFocusPainted(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.setFocusPainted(false);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        rbtnIdDoenca.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroupDoenca.add(rbtnIdDoenca);
        rbtnIdDoenca.setText("Id");
        rbtnIdDoenca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnIdDoencaItemStateChanged(evt);
            }
        });
        rbtnIdDoenca.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnIdDoencaStateChanged(evt);
            }
        });

        rbtnDoenca.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroupDoenca.add(rbtnDoenca);
        rbtnDoenca.setText("Doença");
        rbtnDoenca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnDoencaItemStateChanged(evt);
            }
        });
        rbtnDoenca.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnDoencaStateChanged(evt);
            }
        });
        rbtnDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDoencaActionPerformed(evt);
            }
        });

        txtSintoma.setSelectedTextColor(new java.awt.Color(204, 255, 255));
        txtSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSintomaActionPerformed(evt);
            }
        });

        rbtnSintoma.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroupSintoma.add(rbtnSintoma);
        rbtnSintoma.setText("Sintoma");
        rbtnSintoma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnSintomaItemStateChanged(evt);
            }
        });
        rbtnSintoma.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnSintomaStateChanged(evt);
            }
        });
        rbtnSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSintomaActionPerformed(evt);
            }
        });

        rbtnIdSintoma.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroupSintoma.add(rbtnIdSintoma);
        rbtnIdSintoma.setText("Id");
        rbtnIdSintoma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnIdSintomaItemStateChanged(evt);
            }
        });
        rbtnIdSintoma.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnIdSintomaStateChanged(evt);
            }
        });

        lblTextoSintoma.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoSintoma.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblTextoSintoma.setText("Digite o nome do sintoma:");

        javax.swing.GroupLayout jpanelInput1Layout = new javax.swing.GroupLayout(jpanelInput1);
        jpanelInput1.setLayout(jpanelInput1Layout);
        jpanelInput1Layout.setHorizontalGroup(
            jpanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelInput1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jpanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTextoSintoma)
                    .addComponent(lblTextoDoenca)
                    .addGroup(jpanelInput1Layout.createSequentialGroup()
                        .addGroup(jpanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanelInput1Layout.createSequentialGroup()
                        .addComponent(txtDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnDoenca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnIdDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelInput1Layout.createSequentialGroup()
                        .addComponent(txtSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnSintoma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnIdSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jpanelInput1Layout.setVerticalGroup(
            jpanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelInput1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTextoDoenca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnDoenca)
                    .addComponent(rbtnIdDoenca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextoSintoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnSintoma)
                    .addComponent(rbtnIdSintoma))
                .addGap(18, 18, 18)
                .addGroup(jpanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelInput1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpanelTitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelInput1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        th.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoencaActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void rbtnIdDoencaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnIdDoencaItemStateChanged
        lblTextoDoenca.setText("Digite o Id da doença:");
    }//GEN-LAST:event_rbtnIdDoencaItemStateChanged

    private void rbtnIdDoencaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnIdDoencaStateChanged

    }//GEN-LAST:event_rbtnIdDoencaStateChanged

    private void rbtnDoencaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnDoencaItemStateChanged
        lblTextoDoenca.setText("Digite o nome da doença:");
    }//GEN-LAST:event_rbtnDoencaItemStateChanged

    private void rbtnDoencaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnDoencaStateChanged

    }//GEN-LAST:event_rbtnDoencaStateChanged

    private void rbtnDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDoencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDoencaActionPerformed

    private void txtSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSintomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSintomaActionPerformed

    private void rbtnSintomaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnSintomaItemStateChanged
        lblTextoSintoma.setText("Digite o nome do sintoma:");
    }//GEN-LAST:event_rbtnSintomaItemStateChanged

    private void rbtnSintomaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnSintomaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSintomaStateChanged

    private void rbtnSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSintomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSintomaActionPerformed

    private void rbtnIdSintomaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnIdSintomaItemStateChanged
        lblTextoSintoma.setText("Digite o Id do sintoma:");
    }//GEN-LAST:event_rbtnIdSintomaItemStateChanged

    private void rbtnIdSintomaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnIdSintomaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnIdSintomaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVincularDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVincularDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVincularDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVincularDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVincularDoenca(new TelaHome()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.ButtonGroup buttonGroupDoenca;
    private javax.swing.ButtonGroup buttonGroupSintoma;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jpanelInput1;
    private javax.swing.JPanel jpanelTitulo3;
    private javax.swing.JLabel lblTextoDoenca;
    private javax.swing.JLabel lblTextoSintoma;
    private javax.swing.JRadioButton rbtnDoenca;
    private javax.swing.JRadioButton rbtnIdDoenca;
    private javax.swing.JRadioButton rbtnIdSintoma;
    private javax.swing.JRadioButton rbtnSintoma;
    private javax.swing.JTextField txtDoenca;
    private javax.swing.JTextField txtSintoma;
    // End of variables declaration//GEN-END:variables
}
