/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author 04590876060
 */
public class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    public TelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpanelBotoes = new javax.swing.JPanel();
        btnPesquisarDoenca = new javax.swing.JButton();
        btnPesquisarSintoma = new javax.swing.JButton();
        btnCadastrarDoenca = new javax.swing.JButton();
        btnCadastrarSintoma = new javax.swing.JButton();
        btnVincularDoenca = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnDetectarDoencas = new javax.swing.JButton();
        btnPesquisarVinculos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Home");

        jpanelTitulo.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DiagWeb");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        javax.swing.GroupLayout jpanelTituloLayout = new javax.swing.GroupLayout(jpanelTitulo);
        jpanelTitulo.setLayout(jpanelTituloLayout);
        jpanelTituloLayout.setHorizontalGroup(
            jpanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelTituloLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelTituloLayout.setVerticalGroup(
            jpanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelTituloLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jpanelBotoes.setBackground(new java.awt.Color(153, 153, 255));

        btnPesquisarDoenca.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnPesquisarDoenca.setText("Pesquisar doença");
        btnPesquisarDoenca.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPesquisarDoenca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarDoenca.setFocusPainted(false);
        btnPesquisarDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarDoencaActionPerformed(evt);
            }
        });

        btnPesquisarSintoma.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnPesquisarSintoma.setText("Pesquisar sintoma");
        btnPesquisarSintoma.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPesquisarSintoma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarSintoma.setFocusPainted(false);
        btnPesquisarSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarSintomaActionPerformed(evt);
            }
        });

        btnCadastrarDoenca.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnCadastrarDoenca.setText("Cadastrar doença");
        btnCadastrarDoenca.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnCadastrarDoenca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarDoenca.setFocusPainted(false);
        btnCadastrarDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarDoencaActionPerformed(evt);
            }
        });

        btnCadastrarSintoma.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnCadastrarSintoma.setText("Cadastrar sintoma");
        btnCadastrarSintoma.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnCadastrarSintoma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarSintoma.setFocusPainted(false);
        btnCadastrarSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarSintomaActionPerformed(evt);
            }
        });

        btnVincularDoenca.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnVincularDoenca.setText("Vincular D&S");
        btnVincularDoenca.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnVincularDoenca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVincularDoenca.setFocusPainted(false);
        btnVincularDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVincularDoencaActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setFocusPainted(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnDetectarDoencas.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnDetectarDoencas.setText("Detectar doenças");
        btnDetectarDoencas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnDetectarDoencas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetectarDoencas.setFocusPainted(false);
        btnDetectarDoencas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetectarDoencasActionPerformed(evt);
            }
        });

        btnPesquisarVinculos.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnPesquisarVinculos.setText("Pesquisar vinculos");
        btnPesquisarVinculos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPesquisarVinculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarVinculos.setFocusPainted(false);
        btnPesquisarVinculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarVinculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelBotoesLayout = new javax.swing.GroupLayout(jpanelBotoes);
        jpanelBotoes.setLayout(jpanelBotoesLayout);
        jpanelBotoesLayout.setHorizontalGroup(
            jpanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelBotoesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jpanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrarDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetectarDoencas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarVinculos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVincularDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jpanelBotoesLayout.setVerticalGroup(
            jpanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelBotoesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPesquisarSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrarSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVincularDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarVinculos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetectarDoencas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVincularDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVincularDoencaActionPerformed
        TelaVincularDoenca tdds = new TelaVincularDoenca(this);
        this.setVisible(false);
        tdds.setVisible(true);
    }//GEN-LAST:event_btnVincularDoencaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesquisarDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarDoencaActionPerformed
        TelaPesquisarDoenca tpd = new TelaPesquisarDoenca(this);
        this.setVisible(false);
        tpd.setVisible(true);
    }//GEN-LAST:event_btnPesquisarDoencaActionPerformed

    private void btnPesquisarSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarSintomaActionPerformed
        TelaPesquisarSintoma tps = new TelaPesquisarSintoma(this);
        this.setVisible(false);
        tps.setVisible(true);
    }//GEN-LAST:event_btnPesquisarSintomaActionPerformed

    private void btnCadastrarDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarDoencaActionPerformed
        TelaCadastrarDoenca tcd = new TelaCadastrarDoenca(this);
        this.setVisible(false);
        tcd.setVisible(true);
    }//GEN-LAST:event_btnCadastrarDoencaActionPerformed

    private void btnCadastrarSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarSintomaActionPerformed
        TelaCadastrarSintoma tcs = new TelaCadastrarSintoma(this);
        this.setVisible(false);
        tcs.setVisible(true);
    }//GEN-LAST:event_btnCadastrarSintomaActionPerformed

    private void btnDetectarDoencasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetectarDoencasActionPerformed
        TelaDetectarDoenca tdd = new TelaDetectarDoenca(this);
        this.setVisible(false);
        tdd.setVisible(true);
    }//GEN-LAST:event_btnDetectarDoencasActionPerformed

    private void btnPesquisarVinculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarVinculosActionPerformed
        TelaPesquisarVinculo tvd = new TelaPesquisarVinculo(this);
        this.setVisible(false);
        tvd.setVisible(true);
    }//GEN-LAST:event_btnPesquisarVinculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarDoenca;
    private javax.swing.JButton btnCadastrarSintoma;
    private javax.swing.JButton btnDetectarDoencas;
    private javax.swing.JButton btnPesquisarDoenca;
    private javax.swing.JButton btnPesquisarSintoma;
    private javax.swing.JButton btnPesquisarVinculos;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVincularDoenca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpanelBotoes;
    private javax.swing.JPanel jpanelTitulo;
    // End of variables declaration//GEN-END:variables
}
